package com.resolvit.ui.utils;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.resolvit.core.entities.Complaint;
import com.resolvit.core.entities.User;
import com.resolvit.core.enums.Category;
import com.resolvit.core.enums.Priority;
import com.resolvit.core.enums.Status;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Generates PDF reports for complaints and analytics.
 * Uses iTextPDF library for professional-grade document generation.
 *
 * @author ResolvIt Team
 * @version 1.0.0
 */
public final class PDFGenerator {

    private static final Logger log = LoggerFactory.getLogger(PDFGenerator.class);

    // Colors
    private static final BaseColor PRIMARY_COLOR = new BaseColor(46, 125, 50);
    private static final BaseColor HEADER_BG = new BaseColor(46, 125, 50);
    private static final BaseColor HEADER_TEXT = BaseColor.WHITE;
    private static final BaseColor ALT_ROW = new BaseColor(245, 245, 245);

    // Fonts
    private static final Font TITLE_FONT = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, PRIMARY_COLOR);
    private static final Font SUBTITLE_FONT = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.GRAY);
    private static final Font HEADER_FONT = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, HEADER_TEXT);
    private static final Font BODY_FONT = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, BaseColor.BLACK);
    private static final Font BOLD_FONT = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.BLACK);

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final DateTimeFormatter DATETIME_FORMAT = DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm");

    private PDFGenerator() {
        // Utility class - prevent instantiation
    }

    /**
     * Generates a complaint report PDF.
     *
     * @param complaints  the list of complaints to include
     * @param generatedBy the user generating the report
     * @param outputPath  the output file path
     * @param reportTitle the report title
     * @throws Exception if PDF generation fails
     */
    public static void generateComplaintReport(
            List<Complaint> complaints,
            User generatedBy,
            String outputPath,
            String reportTitle) throws Exception {

        log.info("Generating complaint report: {}", reportTitle);

        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        PdfWriter.getInstance(document, new FileOutputStream(outputPath));
        document.open();

        // Add header
        addHeader(document, reportTitle);

        // Add metadata
        addMetadata(document, generatedBy, complaints.size());

        // Add summary statistics
        addSummaryStats(document, complaints);

        // Add complaints table
        addComplaintsTable(document, complaints);

        // Add category breakdown
        addCategoryBreakdown(document, complaints);

        // Add footer
        addFooter(document);

        document.close();
        log.info("Report generated successfully: {}", outputPath);
    }

    /**
     * Adds the report header.
     */
    private static void addHeader(Document document, String title) throws DocumentException {
        // Title
        Paragraph titlePara = new Paragraph(title, TITLE_FONT);
        titlePara.setAlignment(Element.ALIGN_CENTER);
        document.add(titlePara);

        // Tagline
        Paragraph tagline = new Paragraph("ResolvIt - Complaint Management System", SUBTITLE_FONT);
        tagline.setAlignment(Element.ALIGN_CENTER);
        tagline.setSpacingAfter(10);
        document.add(tagline);

        // Green line separator
        PdfPTable line = new PdfPTable(1);
        line.setWidthPercentage(100);
        PdfPCell lineCell = new PdfPCell();
        lineCell.setBorderColor(PRIMARY_COLOR);
        lineCell.setBorderWidth(2);
        lineCell.setBorder(Rectangle.BOTTOM);
        lineCell.setFixedHeight(5);
        line.addCell(lineCell);
        line.setSpacingAfter(20);
        document.add(line);
    }

    /**
     * Adds report metadata.
     */
    private static void addMetadata(Document document, User generatedBy, int complaintCount)
            throws DocumentException {

        PdfPTable metaTable = new PdfPTable(2);
        metaTable.setWidthPercentage(100);
        metaTable.setSpacingAfter(15);

        addMetaRow(metaTable, "Generated By:", generatedBy != null ? generatedBy.getName() : "System");
        addMetaRow(metaTable, "Generated On:", LocalDateTime.now().format(DATETIME_FORMAT));
        addMetaRow(metaTable, "Total Complaints:", String.valueOf(complaintCount));

        document.add(metaTable);
    }

    /**
     * Adds a metadata row.
     */
    private static void addMetaRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, BOLD_FONT));
        labelCell.setBorder(Rectangle.NO_BORDER);
        labelCell.setPadding(3);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, BODY_FONT));
        valueCell.setBorder(Rectangle.NO_BORDER);
        valueCell.setPadding(3);
        table.addCell(valueCell);
    }

    /**
     * Adds summary statistics section.
     */
    private static void addSummaryStats(Document document, List<Complaint> complaints)
            throws DocumentException {

        Paragraph heading = new Paragraph("Summary Statistics", BOLD_FONT);
        heading.setSpacingBefore(10);
        heading.setSpacingAfter(10);
        document.add(heading);

        // Calculate stats
        Map<Status, Long> statusCounts = complaints.stream()
                .collect(Collectors.groupingBy(Complaint::getStatus, Collectors.counting()));

        Map<Priority, Long> priorityCounts = complaints.stream()
                .collect(Collectors.groupingBy(Complaint::getPriority, Collectors.counting()));

        // Status table
        PdfPTable statsTable = new PdfPTable(5);
        statsTable.setWidthPercentage(100);
        statsTable.setSpacingAfter(15);

        // Header row
        for (Status status : Status.values()) {
            PdfPCell cell = new PdfPCell(new Phrase(status.getDisplayName(), HEADER_FONT));
            cell.setBackgroundColor(hexToBaseColor(status.getHexColor()));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(8);
            statsTable.addCell(cell);
        }

        // Value row
        for (Status status : Status.values()) {
            long count = statusCounts.getOrDefault(status, 0L);
            PdfPCell cell = new PdfPCell(new Phrase(String.valueOf(count), BOLD_FONT));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(8);
            statsTable.addCell(cell);
        }

        document.add(statsTable);
    }

    /**
     * Adds the main complaints table.
     */
    private static void addComplaintsTable(Document document, List<Complaint> complaints)
            throws DocumentException {

        Paragraph heading = new Paragraph("Complaint Details", BOLD_FONT);
        heading.setSpacingBefore(10);
        heading.setSpacingAfter(10);
        document.add(heading);

        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1, 3, 2, 1.5f, 1.5f, 2, 1.5f});

        // Header row
        String[] headers = {"#", "Title", "Category", "Priority", "Status", "Submitted By", "Date"};
        for (String header : headers) {
            addHeaderCell(table, header);
        }

        // Data rows
        int i = 1;
        for (Complaint c : complaints) {
            boolean altRow = (i % 2 == 0);

            addDataCell(table, String.valueOf(i++), altRow);
            addDataCell(table, truncateText(c.getTitle(), 30), altRow);
            addDataCell(table, c.getCategory().getDisplayName(), altRow);

            // Colored priority cell
            PdfPCell priorityCell = new PdfPCell(new Phrase(
                    c.getPriority().getDisplayName(), BODY_FONT));
            priorityCell.setBackgroundColor(hexToBaseColor(c.getPriority().getHexColor()));
            priorityCell.setPadding(5);
            priorityCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(priorityCell);

            // Colored status cell
            PdfPCell statusCell = new PdfPCell(new Phrase(
                    c.getStatus().getDisplayName(), BODY_FONT));
            statusCell.setBackgroundColor(hexToBaseColor(c.getStatus().getHexColor()));
            statusCell.setPadding(5);
            statusCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(statusCell);

            String submitter = c.isAnonymous() ? "Anonymous" :
                    (c.getSubmittedBy() != null ? c.getSubmittedBy().getName() : "Unknown");
            addDataCell(table, submitter, altRow);

            String date = c.getCreatedAt() != null ?
                    c.getCreatedAt().format(DATE_FORMAT) : "N/A";
            addDataCell(table, date, altRow);
        }

        document.add(table);
    }

    /**
     * Adds category breakdown section.
     */
    private static void addCategoryBreakdown(Document document, List<Complaint> complaints)
            throws DocumentException {

        document.newPage();

        Paragraph heading = new Paragraph("Category Breakdown", BOLD_FONT);
        heading.setSpacingBefore(20);
        heading.setSpacingAfter(10);
        document.add(heading);

        Map<Category, Long> categoryCounts = complaints.stream()
                .collect(Collectors.groupingBy(Complaint::getCategory, Collectors.counting()));

        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(60);
        table.setHorizontalAlignment(Element.ALIGN_LEFT);
        table.setWidths(new float[]{3, 1, 1.5f});

        addHeaderCell(table, "Category");
        addHeaderCell(table, "Count");
        addHeaderCell(table, "Percentage");

        int total = complaints.size();
        int row = 0;
        for (Category cat : Category.values()) {
            boolean altRow = (row++ % 2 == 0);
            long count = categoryCounts.getOrDefault(cat, 0L);
            double percentage = total > 0 ? (count * 100.0 / total) : 0;

            addDataCell(table, cat.getDisplayName(), altRow);
            addDataCell(table, String.valueOf(count), altRow);
            addDataCell(table, String.format("%.1f%%", percentage), altRow);
        }

        document.add(table);
    }

    /**
     * Adds the report footer.
     */
    private static void addFooter(Document document) throws DocumentException {
        Paragraph footer = new Paragraph(
                "This report was generated by ResolvIt Complaint Management System. " +
                        "For any queries, contact support@resolvit.com",
                new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC, BaseColor.GRAY)
        );
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(30);
        document.add(footer);
    }

    /**
     * Adds a header cell to a table.
     */
    private static void addHeaderCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(HEADER_BG);
        cell.setPadding(8);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    /**
     * Adds a data cell to a table.
     */
    private static void addDataCell(PdfPTable table, String text, boolean altRow) {
        PdfPCell cell = new PdfPCell(new Phrase(text, BODY_FONT));
        if (altRow) {
            cell.setBackgroundColor(ALT_ROW);
        }
        cell.setPadding(5);
        table.addCell(cell);
    }

    /**
     * Converts a hex color string to BaseColor.
     */
    private static BaseColor hexToBaseColor(String hex) {
        if (hex == null || hex.isEmpty()) {
            return BaseColor.WHITE;
        }
        hex = hex.replace("#", "");
        try {
            int r = Integer.parseInt(hex.substring(0, 2), 16);
            int g = Integer.parseInt(hex.substring(2, 4), 16);
            int b = Integer.parseInt(hex.substring(4, 6), 16);
            return new BaseColor(r, g, b);
        } catch (Exception e) {
            return BaseColor.WHITE;
        }
    }

    /**
     * Truncates text to a maximum length.
     */
    private static String truncateText(String text, int maxLength) {
        if (text == null) return "";
        if (text.length() <= maxLength) return text;
        return text.substring(0, maxLength - 3) + "...";
    }

    /**
     * Generates a simple summary report.
     *
     * @param outputPath the output file path
     * @param title      the report title
     * @param content    the report content as key-value pairs
     * @throws Exception if PDF generation fails
     */
    public static void generateSimpleReport(
            String outputPath,
            String title,
            Map<String, String> content) throws Exception {

        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(outputPath));
        document.open();

        addHeader(document, title);

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(80);
        table.setSpacingBefore(20);

        for (Map.Entry<String, String> entry : content.entrySet()) {
            addMetaRow(table, entry.getKey(), entry.getValue());
        }

        document.add(table);
        addFooter(document);
        document.close();
    }
}
